[build]
  publish = "."

[[redirects]]
  from = "/products/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/index.html"
  status = 200
